name: store
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-174.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  iconsax: ^0.0.8
  get: ^4.6.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  multi_image_picker_plus: ^0.0.4
  firebase_app_check: ^0.2.1+13
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  mailer: ^6.1.0
  otp: ^3.1.4
  enefty_icons: ^1.0.7
  flutter_map: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  random_avatar: ^0.0.8
  shimmer: ^3.0.0
  google_fonts: ^6.2.0
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/localyphoto/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/Logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true